export enum ErrorCode {
  NONE = "NONE",
  FORBIDDEN = "FORBIDDEN",
  SPRINT_NOT_FOUND = "SPRINT_NOT_FOUND",
  TASK_NOT_FOUND = "TASK_NOT_FOUND",
  INVALID_INPUT = "INVALID_INPUT",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}