export const ERROR_CODE = Object.freeze({
    AUTHENTICATION: "AUTHENTICATION_ERR",
    AUTHORIZATION: "AUTHORIZATION_ERR",
    JSON_PARSER: "JSON_PARSER_ERR",
    ROUTING: "ROUTING_ERR",
    INTERNAL: "GATEWAY_ERR",
    CRITICAL: "CRITICAL_ERR"
} as const);